version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    container_name: web-docker
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data #pgdata ignored with .gitignore file
    container_name: pg-docker

    env_file:
      - ./.env
    ports:
      - '5432:5432'

volumes:
  pg-data:


