version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    container_name: web-docker
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data #pgdata ignored with .gitignore file
    container_name: pg-docker
    environment:
      POSTGRES_DB: pgdata
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg1234
    ports:
      - '5432:5432'

