version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    container_name: web-app
    networks:
      - back-end
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: pg-data
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - back-end

volumes:
  pg-data:

networks:
  back-end:
