version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  my-app:
    build:
      context: .
    #ports:
      #- '8000:8000'
    volumes:
      - ./:/app
