version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  mail-app:
    build:
      context: .
    restart: always
   # ports:
     # - '8000-8080:8080'
    volumes:
      - ./:/app
    env_file:
       - ./.env


