version: '3'
services:
  node-server:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - PORT=8080
    #env_file:
    # - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=anroot
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
